version: "2"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    hostname: nginx
    restart: always
    container_name: nginx
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ./client/build:/usr/share/nginx/html
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/nginx_my.conf:/etc/nginx/service.conf
    ports:
      - 80:80
      - 443:443
    env_file:
      - ./nginx/nginx.env
    networks:
      - app-network

  nodejs:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: Node
    volumes:
      - ./common:/usr/src/app/common
      - /usr/src/app/actual/node_modules
    restart: always
    ports:
      - 7101:7101

  react:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: React
    volumes:
      - ./common:/usr/src/app/common
      - /usr/src/app/actual/node_modules

networks:
  app-network:
    driver: bridge
